title = "andrew luo"

[params.author]
name = "andrew luo"
image = "img/me.png"
headline = "engineer, sound-smith, essays"
bio = "engineer, sound-smith, essays"
links = [
	{ email = "andrew.luo25@gmail.com" },
	{ linkedin = "https://www.linkedin.com/in/andluo/" },
	{ instagram = "https://www.instagram.com/andrewlu.ooo/" },
	{ github = "https://github.com/andrewlu000" }
]
