[[main]]
	name = "publications"
	pageRef = "publications"
	weight = 20

[[main]]
	name = "papers"
	pageRef = "papers"
	weight = 25

[[main]]
	name = "notes"
	url = "https://notes.andluo.com/"
	weight = 30

[[main]]
	name = "bookshelf"
	url = "https://notes.andluo.com/readwise"
	weight = 40

[[main]]
	identifier = "appearance"
	weight = 98
	[main.params]
		action = "appearance"
		icon = "moon"
		showName = false


[[main]]
	identifier = "search"
	weight = 99
	[main.params]
		action = "search"
		icon = "search"
